### ISSUE TITLE
Miui 8 Aplicacion scanner

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-8.0-SPANISH#173]
Pongo las fotos de lo que esta en ingles:

![screenshot_2016-06-04-13-06-39-773_com xiaomi scanner](https://cloud.githubusercontent.com/assets/18089036/15799236/cd883602-2a55-11e6-99ce-b804921008fb.png)
![screenshot_2016-06-04-13-06-56-390_com xiaomi scanner](https://cloud.githubusercontent.com/assets/18089036/15799235/cd872f6e-2a55-11e6-8c51-067d03642822.png)
![screenshot_2016-06-04-13-07-07-372_com xiaomi scanner](https://cloud.githubusercontent.com/assets/18089036/15799238/dacd50cc-2a55-11e6-809a-3e3d6bd5a31d.png)

**Comment by jamflux** [comment]
Esa app escaner no la tenemos en el repositorio.
Mándamela y la agrego.

**Comment by jamflux** [comment]
Listo, se cierra el caso.
