### ISSUE TITLE
Cámara

### ISSUE THREAD

**Issue by ams02** [ingbrzy/MA-XML-8.0-SPANISH#263]
La app de cámara no tiene los efectos que se supone que debe tener es decir, los filtros

**Comment by jamflux** [comment]
Acá puedes reportar casos afines a la traducción, revise la app y  está completa con lo filtros y demás.
Cierro el caso porque tu reporte no tiene nada que ver con la traducción.
Para comentar problemas con la ROM en sí hazle en el foro de xiaomi.eu.
Acá sólo es traducción.
