### ISSUE TITLE
Textos aún no traducidos en MIUI 8

### ISSUE THREAD

**Issue by uriana** [ingbrzy/MA-XML-8.0-SPANISH#277]
Adjunto unas capturas de pantalla con textos aún no traducidos.
Muchisimas gracias por vuetro trabajo.
Saludos

![screenshot_2016-06-21-10-02-41-059_com android quicksearchbox](https://cloud.githubusercontent.com/assets/15260759/16256002/05d7b922-384f-11e6-9ac6-14b41c14d32f.jpg)
![screenshot_2016-06-21-10-00-58-513_com miui home](https://cloud.githubusercontent.com/assets/15260759/16256003/0b6009d0-384f-11e6-8be9-af94272527dc.jpg)
![screenshot_2016-06-21-10-32-53-287_com miui securitycore](https://cloud.githubusercontent.com/assets/15260759/16256009/0f7a372a-384f-11e6-95df-29b7bf482346.jpg)
![screenshot_2016-06-21-17-43-44-468_com jv flyne](https://cloud.githubusercontent.com/assets/15260759/16256013/13a4dc60-384f-11e6-9261-bbe54ee33169.jpg)
![screenshot_2016-06-21-09-57-49-965_com android contacts](https://cloud.githubusercontent.com/assets/15260759/16256015/17765f08-384f-11e6-80b4-eec8c08de4e8.jpg)

**Comment by Infante007** [comment]
hola @uriana  que móvil tienes?

**Comment by uriana** [comment]
Ups, un Redmi Note 2. Lo siento

**Comment by Infante007** [comment]
Bueno en principio para mañana tienes todo actualizado al Español
Algunas veces no ocurre porque son muchas lineas y muchas carpetas .
Cualquier cosa mañana nos avisas.
un abrazo
