### ISSUE TITLE
Faltan traducciónes (contactos y mensajería)

### ISSUE THREAD

**Issue by KrL0z69** [ingbrzy/MA-XML-8.0-SPANISH#301]
En el área de editar contacto:

![img_20160622_114100](https://cloud.githubusercontent.com/assets/20027189/16275318/24a973ca-386f-11e6-9ad6-96c224a308c6.jpg)
![img_20160622_114308](https://cloud.githubusercontent.com/assets/20027189/16275338/348b6640-386f-11e6-9247-c3360540c051.jpg)

En la aplicación de mensajes y sus configuraciones:
![img_20160622_114359](https://cloud.githubusercontent.com/assets/20027189/16275373/56b63d8a-386f-11e6-8d57-7ebff4aef1dd.jpg)
![img_20160622_114430](https://cloud.githubusercontent.com/assets/20027189/16275381/611d5e5c-386f-11e6-903c-ec8ab4d5da5f.jpg)
![screenshot_2016-06-22-11-44-43-427_com android mms](https://cloud.githubusercontent.com/assets/20027189/16275388/6a3f824e-386f-11e6-8572-c77bd3eb560a.png)
![screenshot_2016-06-22-11-45-01-276_com android mms](https://cloud.githubusercontent.com/assets/20027189/16275392/715d9124-386f-11e6-9006-5f6ea169c603.png)

Xiaomi Redmi Note 2.

**Comment by Infante007** [comment]
Esto algunas veces pasa, lo que me enseñas esta traducido, en algunas versiones de moviles al actualizar en vez de aparecer en español ,aparece en ingles.
Mañana me comentas si sigue igual.

**Comment by KrL0z69** [comment]
Muchas gracias por su arduo trabajo, gracias @Infante007 , tenías razón, ya en esta actualización se resolvieron los detalles que emocioné. Al parecer todo va de lujo, claro falta pulirla pero es un excelente trabajo todo el equipo. Para futuros detalles, seguiré pendiente.
UN SALUDO!!

**Comment by Infante007** [comment]
Gracias @KrL0z69 todo es trabajo de equipo no soy yo solo, aunque somos pocos.
Cualquier problema que veas en la traduccion o mejora que veas que se puede hacer en la traduccion sera agradecida.
un saludo
