### ISSUE TITLE
Mi cloud notificación en chino/ mi cloud notification un chinese

### ISSUE THREAD

**Issue by hectoryo** [ingbrzy/MA-XML-8.0-SPANISH#313]
![screenshot_2016-06-26-14-54-34-326_com gsamlabs bbm](https://cloud.githubusercontent.com/assets/5202409/16362462/e4920a88-3baf-11e6-82d6-5ee0661c2bea.png)

**Comment by hectoryo** [comment]
Redmi note 2 Prime

**Comment by Infante007** [comment]
Buenas tardes @hectoryo

**Comment by hectoryo** [comment]
Buenas, si necesitaras algo más de mi parte no dudes en pedirlo, sólo se que salió esa notificación en chino, al abrirlo, me envió a un menu para hacer premium la cuenta MI (menú que por cierto, estaba en inglés) Un saludo.

**Comment by Infante007** [comment]
@hectoryo si puedes manda una pantalla del menú que esta en ingles.
El tema de letras chinas no puedo solucionarlo , tienen que traducirlo antes al ingles

**Comment by hectoryo** [comment]
![screenshot_2016-06-28-10-56-58-027_com miui cloudservice](https://cloud.githubusercontent.com/assets/5202409/16409803/97bf677a-3d1f-11e6-903d-50019947fbb9.jpg)

**Comment by Infante007** [comment]
@hectoryo lo estuve buscando y creo que es tema de conexión a internet, no esta en el teléfono.
Así que no hay forma de traducirlo.
