### ISSUE TITLE
Mi Remote

### ISSUE THREAD

**Issue by ams02** [ingbrzy/MA-XML-8.0-SPANISH#314]
Mi remote cuando se configura un mando de TV hay apartados en chino y ingles

**Comment by Infante007** [comment]
Hola @ams02 ,es cierto hay temas en chino y ingles.
Ya el tema se comento en el foro de miui.eu.
las palabras en ingles pueden ser traducidas, las chinas hay que esperar que las traduzcan.
Mándame pantallas de lo que quieres ver traducido.
