### ISSUE TITLE
Estable 7.3.2.0 Xiaomi Mi note Pro

### ISSUE THREAD

**Issue by moca1974** [ingbrzy/MA-XML-8.0-SPANISH#315]
La ultima estable para el Xiaomi Mi note pro, estable 7.3.2.0 los conmutadores no estan traducidos al español, la barra de busqueda si. Los demas idiomas si van bien traducidos. Excelente trabajo, gracias.
<a href="http://s224.photobucket.com/user/crispin01/media/Screenshot_2016-06-27-01-02-49_com.miui.home.png.html" target="_blank"><img src="http://i224.photobucket.com/albums/dd121/crispin01/Screenshot_2016-06-27-01-02-49_com.miui.home.png" border="0" alt=" photo Screenshot_2016-06-27-01-02-49_com.miui.home.png"/></a>

**Comment by moca1974** [comment]
Para Xiaomi Mi Note Pro, 7.3.2.0. Gracias, excelente trabajo.

**Comment by Infante007** [comment]
Hola @moca1974 ,es raro, ésa parte tendría que estar traducida .
Algunas veces en las actualizaciones aunque este traducido aparece en ingles en vez de español.
En la siguiente estará solucionado

**Comment by Infante007** [comment]
Una pregunta @moca1974 ¿ es la versión miui 8?

**Comment by moca1974** [comment]
No es 7

**Comment by Infante007** [comment]
Es lo que me parecía, pues lo siento @moca1974 ya se abandono el miui 7 y solo se traduce la miui 8.
Si actualizas a miui 8  esa parte esta traducida
un saludo
