### ISSUE TITLE
Mi remote 

### ISSUE THREAD

**Issue by ams02** [ingbrzy/MA-XML-8.0-SPANISH#317]
Capturas de lo que hay que traducir
![img_20160627_131013](https://cloud.githubusercontent.com/assets/20032556/16377924/35333a2a-3c69-11e6-8c3a-d9073eb75c3b.jpg)
![img_20160627_130811](https://cloud.githubusercontent.com/assets/20032556/16377926/3820211c-3c69-11e6-8372-78c4295c6cc8.jpg)

**Comment by Infante007** [comment]
@ams02  que movil tienes?

**Comment by ams02** [comment]
@Infante007  tengo el Mí 4c

**Comment by Infante007** [comment]
@ams02 estoy en ello, pero con el tema chino hay que esperar que se traduzca al ingles.
Pero hay gente que en el foro se quejaron por lo mismo, así que no creo que tarden en traducirlo.
El tema es que lo que esta en ingles no lo encuentro, así que sigo buscando

**Comment by ams02** [comment]
También hay que traducir para el Mí 4c la app de escaner

**Comment by Infante007** [comment]
No te preocupes @ams02  , la aplicación tenía  un problema pero lo soluciono @jamflux .y en la siguiente actualización estará traducida
