### ISSUE TITLE
6.6.23 Mi Max Hydrogen sin traducir

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-8.0-SPANISH#318]
1:
![screenshot_2016-06-27-19-00-57-396_com android cellbroadcastreceiver](https://cloud.githubusercontent.com/assets/4967467/16389146/d3a51470-3c9c-11e6-914c-4f82c664d09a.png)
2: Get weather Info
![screenshot_2016-06-27-19-01-04-738_com android cellbroadcastreceiver](https://cloud.githubusercontent.com/assets/4967467/16389148/d6cca8f2-3c9c-11e6-9336-87d36bef90e8.png)
3: Varias cosas en opciones de desarrollo:
![screenshot_2016-06-27-19-05-20-146_com android settings](https://cloud.githubusercontent.com/assets/4967467/16389149/d7b2cddc-3c9c-11e6-8173-c7cc2d044817.png)
![screenshot_2016-06-27-19-05-28-691_com android settings](https://cloud.githubusercontent.com/assets/4967467/16389151/d963bff6-3c9c-11e6-813f-ed39f9ef5582.png)
![screenshot_2016-06-27-19-05-44-697_com android settings](https://cloud.githubusercontent.com/assets/4967467/16389153/da813a08-3c9c-11e6-8df0-e57e04146436.png)
4:Assist & voice input y sus menús:
![screenshot_2016-06-27-19-36-24-359_com android settings](https://cloud.githubusercontent.com/assets/4967467/16389512/96628fa0-3c9e-11e6-8136-f93251ad5481.png)
![screenshot_2016-06-27-19-36-30-390_com android settings](https://cloud.githubusercontent.com/assets/4967467/16389513/9738bee0-3c9e-11e6-938b-62dd6ff99db7.png)

**Comment by Infante007** [comment]
@jlmcr87 buenas tardes
