### ISSUE TITLE
Problema con la sim

### ISSUE THREAD

**Issue by Magdalenaherre** [ingbrzy/MA-XML-8.0-SPANISH#319]
Tengo un redmi note mtk y al actualizar a miui8 ha dejado de funcionar la SIM, he revertido a míui 7 restableciendo la memoria y sigue sin funcionar, en otros móviles funciona perfectamente

**Comment by Infante007** [comment]
Buenas noches @Magdalenaherre  ,aqui solo solucionamos problemas con la traduccion.
Ve al foro miui.eu y pon la pregunta haber que solucion te dan.
un saludo
