### ISSUE TITLE
Falta de traducir subapartado wifi de la ventana de notificaciones

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-8.0-SPANISH#321]
Hola amigos, antes de todo gracias por traducir la ROM eso lo primero sin vosotros las roms para el redmi note 3 MTK estarían en chino o inglés xD.

Bueno les comento, al bajar la cortina de notificaciones en el toggle de Wifi, si pincha uno en la mini flechita abajo a la derecha del simbolo de toggle se abre una ventana que está en ingles.
Imágenes:
![screenshot_2016-06-24-04-27-33-380_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/11967463/16519925/b49aabc4-3f8c-11e6-9f7e-8db2b5b14a8f.jpg)
![screenshot_2016-06-24-04-27-44-926_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/11967463/16519927/b6f79fa8-3f8c-11e6-8734-972cc1bfc501.jpg)

Muchas gracias y un saludo, estais haciendo un trabajo extraordinario para la comunidad, si admitis donaciones comunicarlo.

**Comment by Infante007** [comment]
Hola @marcosmanteca  da gusto ver que hay gente que agradece el trabajo.
Te avisare cuando lo tenga solucionado y en la siguiente actualizacion estara solucionado.
La donacion en sobre B que si no tengo que declararlo , no te preocupes lo hago gratis.
un saludo

**Comment by Infante007** [comment]
Listo, @marcosmanteca  ya esta arrelgado ,la proxima semana estara en la siguiente rom.
Cualquier cosa que veas o mejora que se puede hacer en la traduccion me lo dices.
