### ISSUE TITLE
Por traducir

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-8.0-SPANISH#323]
Ajustes->Mas-> Transmisiones de emergencia-> Algunas opciones están en inglés.

**Comment by jamflux** [comment]
Hola. Gracias por informar.
Manda una captura de pantalla.
Seguí las indicaciones y mi teléfono no tiene ese apartado.

**Comment by jamflux** [comment]
Cierro el caso. No hay capturas ni has comentado las las líneas en inglés para poderlas buscar.
Agradecemos que en la próxima oportunidad des mas detalles y saludes.
