### ISSUE TITLE
Cosas por traducir y algún detalle visual.

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-8.0-SPANISH#324]
Hola muy buenas, cada semana si veo alguna cosilla por pulir colaboraré con vosotros :). 
Acabo de instalar la rom de esta semana y vi lo siguiente:

1.Pone "po"
Y no se si el texto es una pregunta o afirmación, si fuera pregunta en español  son signo de interrogacion principio y final, pero es raro 2 preguntas una en el titulo y otra en la descripcion.
![screenshot_2016-07-08-13-27-27-008_com android updater](https://cloud.githubusercontent.com/assets/11967463/16686688/2527df56-4514-11e6-80d3-3ef4ba8fbf2f.jpg)

2. Tras actualizar y entrar a la agenda vi esto:
![screenshot_2016-07-08-13-52-24-439_com android contacts](https://cloud.githubusercontent.com/assets/11967463/16686737/76ad6b16-4514-11e6-9aa7-d3e1e0551102.jpg)

3. Pone "pressione" no presione.
![screenshot_2016-07-08-13-47-26-845_com android settings](https://cloud.githubusercontent.com/assets/11967463/16686752/8ec92b90-4514-11e6-83bf-060de6424370.jpg)

4. Y esto es mas que todo visual, en mi opinión. Cuando se bloquea una app el mensaje queda bien tal que asi:
![screenshot_2016-07-08-13-51-21-775_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/11967463/16686790/c59145fe-4514-11e6-8026-4bcf399ab6e2.jpg)

Pero cuando se quiere desbloquear, sale muy junto...No seria mejor poner bloq. asi no quedan las 2 palabras seguidas, no es estético:
![screenshot_2016-07-08-14-04-56-797_com teslacoilsw launcher](https://cloud.githubusercontent.com/assets/11967463/16686835/1a7b2972-4515-11e6-8c99-3038b43a230c.png)

Miraré toda la rom por si veo algun detalle más, muchas gracias por vuestro trabajo, cada semana os echaré una mano viendo si salen pequeñas erratas al traducir o en ingles, es normal, son demasiadas cosas. Ya vi que corregieron lo que comenté la semana pasada  jeje :)

Un saludo

**Comment by jamflux** [comment]
Gracias por el feedback.
Todo quedó arreglado.
Los cambios para la próxima actualización.
