### ISSUE TITLE
Sin prisa,

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-8.0-SPANISH#326]
Haber si alguien lo encuentra, no doy con ellos.

![img_20160710_190706](https://cloud.githubusercontent.com/assets/18089036/16714925/d89bc0ac-46d1-11e6-876b-6be49d9e2137.jpg)
![img_20160710_190551](https://cloud.githubusercontent.com/assets/18089036/16714926/e05d132c-46d1-11e6-8bba-b1e1e1734b0e.jpg)
![img_20160710_190523](https://cloud.githubusercontent.com/assets/18089036/16714927/e7b8107c-46d1-11e6-8e18-edc3f8b1cba1.jpg)
![screenshot_2016-07-06-13-19-14-807_com miui cleanmaster](https://cloud.githubusercontent.com/assets/18089036/16714929/fa245004-46d1-11e6-82ce-1342e54400a2.png)

**Comment by jamflux** [comment]
La primera imagen no tiene solución porque lo que está en inglés es contenido online.
La segunda eran app.
La tercera y cuarta no encontré nada al respecto.

**Comment by Infante007** [comment]
bueno algo es algo, gracias amigo
