### ISSUE TITLE
Error al establecer fondo de pantalla

### ISSUE THREAD

**Issue by joepc74** [ingbrzy/MA-XML-8.0-SPANISH#329]
Cuando desde la galería das a establecer como fondo de pantalla, la primera opción pone "aplicar" y debería ser "Establecer como fond ode bloqueo".

**Comment by Infante007** [comment]
Hola @joepc74 , no es lo mismo el fondo de pantalla que el fondo de la pantalla de bloqueo.
Lo estoy mirando y creo que esta bien ,en galeria y si lo quieres poner de fondo de pantalla le das a aplicar y se pone como ¨Fondo de pantalla¨
Si no es lo que dices, pon imagenes y lo vemos

**Comment by joepc74** [comment]
Desde galería, voy a opciones ![screenshot_2016-07-15-10-05-13-074_com miui gallery](https://cloud.githubusercontent.com/assets/20472213/16867767/ffa99f16-4a73-11e6-9e5a-3b5388308a6a.png)
Y elijo Establecer como fondo de pantalla
![screenshot_2016-07-15-10-05-29-045_com miui home](https://cloud.githubusercontent.com/assets/20472213/16867790/3114a0aa-4a74-11e6-9585-7d1211ffcf3d.png)
Ajusto la imagen y cuando doy a aplicar sale:
![screenshot_2016-07-15-10-05-35-164_com miui home](https://cloud.githubusercontent.com/assets/20472213/16867801/3b93ba98-4a74-11e6-9809-68aef87f762d.png)
La primera opción sirve para aplicar como fondo de la pantalla de bloqueo (es la traducción que tiene la oficial) y creo que es la que realmente debería poner.

**Comment by Infante007** [comment]
Continuar escribiendo
Si tienes razón ,ahora te entiendo.
Con la versión de esta semana pasa igual, lo arreglo ahora mismo y para la próxima semana estará solucionado.
Muchas gracias por el aviso

**Comment by joepc74** [comment]
Gracias a vosotros por el trabajo.

**Comment by Infante007** [comment]
Listo @joepc74 ya esta corregido y para la rom del dia 22 estara bien.
Cualquier otro fallo que veas no dudes y nos lo dices.
un saludo
