### ISSUE TITLE
Notificaciones de whatsapp y facebook

### ISSUE THREAD

**Issue by tomynokker** [ingbrzy/MA-XML-8.0-SPANISH#332]
No siempre me llegan las notificaciones de whatsapp o facebook, sólo a veces y cuando no llegan abro la aplicación y llegan todas de golpe.

**Comment by Infante007** [comment]
Hola @tomynokker ,este foro no es para problemas con la rom , si no para la traducciones y problemas que hay en ella. Si ves algún problema en la rom con el idioma nos avisas y lo arreglamos.
Respecto con tu problema puede ser un tema de permisos  ,tienes que dar los permisos en:
Seguridad-Inicio automático
y luego en ajustes-batería y rendimiento-gestión de uso de la batería
Pero bueno este foro es para temas de traducciones, cualquier otro problema es en el foro xioami.eu
