### ISSUE TITLE
Error de escritura navegador Internet nativo

### ISSUE THREAD

**Issue by Rasius93** [ingbrzy/MA-XML-8.0-SPANISH#335]
Al escribir una nueva palabra en el cuadro de texto de arriba, sólo se escribe correctamente desde la página de inicio. 
Si se realiza una nueva búsqueda estando metido previamente en otra web, al escribir en el cuadro de busqueda, la primera letra no la escribe no la detecta

**Comment by Infante007** [comment]
@Rasius93  usas el navegador nativo de miui?

**Comment by jamflux** [comment]
A mi me ha pasado.
Pero no es asunto de la traducción.
Cierro el caso.

**Comment by Rasius93** [comment]
Ahora mismo uso chrome, pero al instalar la ROM probé el que viene de serie con la ROM el navegador miui y sucede este fallo.
