### ISSUE TITLE
Redmi 3S falta por traducir

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-8.0-SPANISH#337]
Redmi 3S, MIUI 8 ultima versión. Al conectar el telefono al pc salen estas opciones en inglés. 

![screenshot_2016-08-01-14-50-10-815_com android settings](https://cloud.githubusercontent.com/assets/4967467/17294497/94e2a326-57f7-11e6-84c1-7cf69ce0c96d.png)

**Comment by Infante007** [comment]
Esta ya traducido ,muchas gracias por avisar
un saludo
