### ISSUE TITLE
Redmi 3S ingles

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-8.0-SPANISH#338]
Hola, no tengo captura pero en el redmi 3S cuando te pide permiso de aplicaciones sale en inglés. Lo podeis arreglar? gracias

**Comment by Infante007** [comment]
creo que ya esta arreglado, ¿pero puedes ser mas preciso?

**Comment by jlmcr87** [comment]
El mensaje que sale cuando una app te pide un permiso, por ejemplo allow whatsapp to use....a eso me refiero. El móvil ya no lo tengo, era para mí cuñado y sólo he visto ese fallejo y el que puse esta mañana. Gracias

**Comment by Infante007** [comment]
ok, ya esta solucionado .
En la siguiente rom estara en español
un saludo
