### ISSUE TITLE
Falta de traducir 1 detalle y una correción de mayus.

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-8.0-SPANISH#340]
hola muy buenas detecte 1 detalle sin traducir. Cuando falla 3 veces la detección de huella (Redmi Note 3) con el móvil bloqueado la pantalla se enciende y pone:

Try again

En vez de "Inténtelo de nuevo".

Cuando ponemos el despertador de la app de Miui cuando suena y tienes que hacer swipe para que deje de tocar pone la siguiente frase:

Deslice Hacia arriba para cerrar

¿No seria mejor eliminar la H mayuscula del "hacia"?. No tiene sentido que esté en mayus.

Seria:      

Deslice hacia arriba para cerrar

Muchas gracias por el gran trabajo que hacéis, os seguiré avisando en detalles como estos, para que quede pulida pulida la rom. Un saludo

**Comment by Infante007** [comment]
Muchas gracias por la ayuda, todo lo que nos digas para mejoras nuestra traduccion ayudara a todos,
Lo segundo esta ya corregido.
Lo primero,¿solo pone Try again? , o la frase es mas larga.

**Comment by marcosmanteca** [comment]
Solo eso, si hace falta te mando captura

**Comment by Infante007** [comment]
no hace falta lo buscare

**Comment by Infante007** [comment]
listo encontrado y cambiado,
muchas gracias @marcosmanteca
