### ISSUE TITLE
Bug email

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-8.0-SPANISH#341]
hello @ingbrzy  as you comment in the forum there is a fault in the mail, it appears many MB and really is not.
You told me it was a failure of the translation, i was looking at but not to be the fault.
You can help me a little?

**Comment by ingbrzy** [comment]
probably https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/8f29990982dfa9c3de46c48f9ed2bac4624902b8

**Comment by Infante007** [comment]
hahaha ok, 
thank you
