### ISSUE TITLE
Para trabajar

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-8.0-SPANISH#342]
![screenshot_2016-08-05-00-09-27-644_com android settings](https://cloud.githubusercontent.com/assets/18089036/17490047/4f4c7bb6-5da1-11e6-8bbf-229b54100884.png)
![screenshot_2016-08-05-00-09-19-875_com android settings](https://cloud.githubusercontent.com/assets/18089036/17490055/53cfb676-5da1-11e6-97be-3310e009bdfe.png)
![screenshot_2016-08-04-20-42-25-423_com xiaomi miplay](https://cloud.githubusercontent.com/assets/18089036/17490065/5bb6d2e8-5da1-11e6-9375-03598a410e60.png)
![screenshot_2016-08-04-20-23-11-627_com android settings](https://cloud.githubusercontent.com/assets/18089036/17490072/6193fc5e-5da1-11e6-8856-ff314771b369.png)
![screenshot_2016-08-04-20-22-49-569_com android settings](https://cloud.githubusercontent.com/assets/18089036/17490080/68079528-5da1-11e6-920c-b075a1d714ad.png)
![screenshot_2016-08-04-20-22-30-556_com android settings](https://cloud.githubusercontent.com/assets/18089036/17490084/6d16e3f2-5da1-11e6-8051-20ce2b28663f.png)

**Comment by jamflux** [comment]
Hay cosas que ya se habían revisado y no había manera de traducir.
Las últimas tres capturas. 
Mejor cierra el caso. O busca las primeras 3 capturas. No me dedicaré a esto. No lo veo relevante.
