### ISSUE TITLE
Algunas traducciones erróneas

### ISSUE THREAD

**Issue by Abismo** [ingbrzy/MA-XML-8.0-SPANISH#345]
Todavía tengo tengo la versión de la semana pasada (xiaomi.eu 6.8.4 | Beta) así que me disculpo de antemano si ya han sido corregidos, pero encontré algunos posibles fallos de traducción:

A la hora de gestionar las notificaciones de una aplicación, hay una opción que dice "Bloquear las notificaciones en la pantalla" cuando debería decir algo como "Notificaciones en pantalla de bloqueo" o "Permitir/Mostrar notificaciones en pantalla de bloqueo".
![screenshot_2016-08-14-11-09-10-108_com android settings](https://cloud.githubusercontent.com/assets/2502938/17648329/99207238-6210-11e6-92e8-4aa5db31aae7.png)

En las opciones de Batería y rendimiento la primera que aparece dice "Encendido" cuando debería decir algo como "Energía".
![screenshot_2016-08-14-11-09-22-585_com android settings](https://cloud.githubusercontent.com/assets/2502938/17648333/a845bd9a-6210-11e6-94a7-b8f53b73a842.png)

Gracias por su estupendo trabajo :+1:

**Comment by Infante007** [comment]
Listo muchas gracias por el aviso, cualquier cosas que ayude a mejoras la traducción me lo comentas.
Un saludo
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/e0060d73c795a257706f099822e6a120add16474
