### ISSUE TITLE
Falta por traducir

### ISSUE THREAD

**Issue by jlmcr87** [ingbrzy/MA-XML-8.0-SPANISH#347]
Hola, falta por traducir y creo que en todos los xiaomi aunque solo lo he podido comprobar en un xiaomi MAX y en un Redmi 3S. Cuando instalas un apk manualmente, el texto sale en inglés:

Gracias!

![whatsapp image 2016-08-19 at 08 05 14](https://cloud.githubusercontent.com/assets/4967467/17800498/0eac232c-65e4-11e6-90cd-99511516baa5.jpeg)

**Comment by Infante007** [comment]
Solucionado, y lo veras en  la siguiente actualización, 
Muchas gracias
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/67922b01d499f928f79af5574019fb6de999cad8
