### ISSUE TITLE
Ayudar a traducir 

### ISSUE THREAD

**Issue by nosijf982** [ingbrzy/MA-XML-8.0-SPANISH#351]
Hola,siento molestar quizás aquí no es el lugar de decir esto (no encontré uno mejor) pero me gustaría ayudar a traducir 
Disculpen las molestias

**Comment by Infante007** [comment]
¿ Ayuda ?, toda la que quieras dar.
¿ Sabes como va el tema de traducir las lineas y demás ?
Yo tampoco sabia y me enseñaron

**Comment by nosijf982** [comment]
Creo que si más o menos,aunque no me vendría mal una ayudita  :P

**Comment by Infante007** [comment]
tienes telegram?

**Comment by nosijf982** [comment]
La verdad es que no jajaja,me lo puedes explicar así un poco por encima aquí

**Comment by jamflux** [comment]
Ponte en telegram y hablamos.

**Comment by Infante007** [comment]
Si hay un teelgram que no tienes ni que instalalar y puedes hablar con nosotros,asi es como me enseño @jamflux

**Comment by nosijf982** [comment]
Ya me lo he creado mi alias es como mi usuario nosiji982

**Comment by Infante007** [comment]
Nos vemos en telegram

**Comment by rdgi** [comment]
Hola, buenas noches.
Yo y un amigo también queremos colaborar. Todavía no me he hecho cuenta en xiaomi.eu.
Qué hace falta?. Lo que no sepamos nos dais pistas y lo aprendemos. 
Cómo me puedo poner en contacto con vosotros en Telegram?
