### ISSUE TITLE
Aplicación Inbox de Google se cierra al eliminar/completar mail

### ISSUE THREAD

**Issue by victorjit** [ingbrzy/MA-XML-8.0-SPANISH#352]
Teniendo el sistema en español, la app inbox da error y se cierra al eliminar o marcar como completado un email. Poniendo el sistema en inglés no ocurre. Hablo de miui 8 estable en un Mi5, en miui 7 no ocurría. Por lo que me dicen también ocurre en las versiones developer.

**Comment by Infante007** [comment]
Entiendo que es el correo nativo de MIUI,
Tengo la semanal y  mirare si ocurre en mi telefono

**Comment by Josexv1** [comment]
@Infante007 Es en la app Inbox de Google, el nuevo "Inbox by Gmail" cuando deslizas un correo para archivar/completar envia un FC.

**Comment by Infante007** [comment]
Pero no se que tiene que ver con la traducción, ya que es una aplicación externa a miui.
Lo que me mosquea que en ingles no de problemas y en español si

**Comment by Infante007** [comment]
Aunque ahora estaba viendo el foro y había un forero español que decía que el lo ponía en inglés y le seguía sin funcionar.
![screenshot_2016-08-24-23-44-47-173_com quoord tapatalkpro activity](https://cloud.githubusercontent.com/assets/18089036/17949250/c789b066-6a54-11e6-82f5-cf7916875aac.png)

**Comment by victorjit** [comment]
Si, he leído a ese forero. Déjalo en standby si quieres, intentaré probar otra vez lo del idioma para asegurar...lo he puesto aquí pq alguien me ha dicho que lo pusiera si no ocurría al cambiar idioma...no sabía que no se tratan apps externas. De todas maneras informaré si verifico lo del idioma.

**Comment by Infante007** [comment]
Ok @victorjit ,muchas gracias por avisar y cualquier cosa aqui estamos.
un saludo
