### ISSUE TITLE
Mejora en notificaciones

### ISSUE THREAD

**Issue by jkmarks** [ingbrzy/MA-XML-8.0-SPANISH#354]
No sé si ya lo habeis cambiado porque hace dos semanas que no lo he actualizado. Pero en notificaciones cambiaría:
- "Leer más" por "Lectura"
- "Brillo" por "Brillo Automático"
- "Compartir" por "Zona Wi-Fi"

Principalmente es porque es mucho más descriptivo. Ya que compartir no ayuda mucho a entender lo que es, etc...

Muchas gracias por su trabajo en esta rom, es asombroso la cantidad de texto traducido.

**Comment by Infante007** [comment]
Hola.
En la segunda palabra  esta brillo solo porque si ponemos tambien Automático se saldria de los margenes.Como mucho para que quede bien se puede poner (Brillo Auto)
¿La primera y la tercera de donde es?

**Comment by Infante007** [comment]
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/064dec49e3d5fa920ab5cd0c4cefb0602d0fd4dd

**Comment by jkmarks** [comment]
Es todo de las notificaciones. Ok gracias

**Comment by Infante007** [comment]
todas las aplicaciones tienen notificaciones, tienes que decir que aplicación es
haz foto

**Comment by marcosmanteca** [comment]
Lo del Brillo Auto me parece genial. Por cierto sé que no va aqui pero alguien sabe como quitar lo colores en los iconos de ajustes, me gustaba más como estaba antes.

**Comment by Infante007** [comment]
Pues ni idea @marcosmanteca ,creo que no se puede, pero pregunta en el foro europeo

**Comment by jamflux** [comment]
Sin captura de pantalla no podemos hacer nada.

**Comment by jkmarks** [comment]
http://i.imgur.com/MOYprd8.jpg

Por si acaso repito, no he actualizado desde hace unas semanas y no sé si lo han rectificado o cambiado.

**Comment by jkmarks** [comment]
Y me gustaría ayudar a traducir, ya que hay bastantes fallos gramaticales en los que me gustaría ayudar. Ya he trabajado en otras páginas como esta así que mas o menos sé como funciona.

**Comment by Infante007** [comment]
¿Hablamos de miui 8?, creo que tu tienes el miui 7

Ayudar todo lo que quieras y te recibimos con los brazos abiertos

**Comment by sonnickoo** [comment]
Leer mas, deberia ser cambiado por modo lectura como el miui 7.3.7

**Comment by marcosmanteca** [comment]
Yo tengo la ultima miui 6.8.25 y pone Modo lectura, está correcto vamos xD

**Comment by Infante007** [comment]
@jkmarks  confirmas que es miui 7.
