### ISSUE TITLE
Posible bug de traducción

### ISSUE THREAD

**Issue by Abismo** [ingbrzy/MA-XML-8.0-SPANISH#356]
En la última ROM semanal, 6.8.25, al ir a Ajustes > Ajustes adicionales > Botones la app Ajustes se congela y cierra. En inglés funciona bien pero en español falla. Sospecho que el fallo podría ser de traducción. Si no es así, perdón por las molestias.

**Comment by Infante007** [comment]
Es verdad, mirare haber que pasa

**Comment by Infante007** [comment]
@Abismo  yo tambien tengo la 6.8.25 , ¿en la anterior funcionaba?

**Comment by Abismo** [comment]
No lo he comprobado en la anterior, lo siento.

**Comment by Infante007** [comment]
ok gracias

**Comment by Abismo** [comment]
En la 6.8.27 ya no ocurre. Todo perfecto por ahora.

**Comment by Infante007** [comment]
¿Como?
¿Saco ignacio una actualización?

**Comment by Abismo** [comment]
Eso parece. He preguntado en el foro de Xiaomi.eu y en HTCMania pero nadie sabe a qué viene la nueva... Sólo para el Mi5 me parece.

**Comment by Infante007** [comment]
Es lo que estaba viendo, el mi 5, asi que es fallo de ellos

**Comment by Abismo** [comment]
Pero el fallo de traducción ha sido reportado en más dispositivos. Si te pasas por el foro verás que hay más, el RNotePro creo...

**Comment by Infante007** [comment]
Bueno entonces cierro y me alegro que no fuera solo en el idioma español.
Un saludo @Abismo
