### ISSUE TITLE
Falta de traducir al instalar una app (Redmi Note 3) y un detalle

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-8.0-SPANISH#357]
Hola buenas, os envió pantallazo, es al instalar cualquier app.

![screenshot_2016-08-26-04-10-56-448_com android packageinstaller](https://cloud.githubusercontent.com/assets/11967463/18006342/69af6cbe-6b9f-11e6-8cf1-d4f777af5eaf.png)

![screenshot_2016-08-26-04-11-09-659_com android packageinstaller](https://cloud.githubusercontent.com/assets/11967463/18006345/6cedcb3c-6b9f-11e6-80e4-adaafd570668.png)

Por cierto habría alguna manera para que en la app de sistema Reloj no quedara tan mal la palabra Temporizador, es que queda pegada pegada a los puntos del menú:

![screenshot_2016-08-26-15-05-20-951_com android deskclock](https://cloud.githubusercontent.com/assets/11967463/18006450/da85b510-6b9f-11e6-9ed2-b8bfbef6040b.png)

Muchas gracias por todo. Un saludo, si veo algo sin traducir aviso inmediatamente.

**Comment by Infante007** [comment]
ok ,lo miro,que movil tienes

**Comment by marcosmanteca** [comment]
Redmi Note 3, gracias.

**Comment by Infante007** [comment]
ok gracias

**Comment by Infante007** [comment]
En un principio todo arreglado para la siguiente actualización.
Lo del temporizador como no pongamos ¿Minutero?

https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/da7e51482162e6b05a1032e3f51b288686bb6d7f
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/cd376ded6e87247a1d95161da0b6e5fee953472d

**Comment by marcosmanteca** [comment]
Uff no sino asi jaja lo dejamos como está, o un diminutivo
