### ISSUE TITLE
App Seguridad palabra Fijar

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-8.0-SPANISH#359]
Hola les escribo de nuevo, en la app de Seguridad no seria mejor que en el botón ponga Optimizar y no Fijar?
Es que no le veo sentido a la palabra fijar ahi.

![screenshot_2016-08-26-15-41-55-603_com miui securitycenter](https://cloud.githubusercontent.com/assets/11967463/18015179/d16d34cc-6bc6-11e6-9baf-1bebcb9b29ea.png)

Gracias

**Comment by Infante007** [comment]
¿Que movil tenias? @marcosmanteca 
Es que cuando traducimos muchas veces no sabemos a que va referido esa palabra,piensa que son lineas y lineas, y luego cuando aparece en la rom pues no cuadra.
Pero para eso estamos aqui ,para solucionar eso.
Lo cambio ahora

**Comment by Infante007** [comment]
Nada no te preocupes @marcosmanteca  ya esta solucionado por @kot7k  , lo que pasa que esta semana los encargados de la rom europea no metieron las actualizaciones del idioma ,asi que no viene incluida las mejoras de esta semana,
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/pull/348/files
