### ISSUE TITLE
Posible error de traducción

### ISSUE THREAD

**Issue by seresias** [ingbrzy/MA-XML-8.0-SPANISH#373]
En el Widget "weather_clock " la humedad ambiente aparece en Polaco con la palabra "wilgotnosc" tal y como se muestra marcado en el recuadro rojo en la imagen siguiente.  

Telefono: Mi Note Pro
Versión de rom: Miui 8 by Xioami.eu 6.8.11|beta

![screenshot_com miui home_marked](https://cloud.githubusercontent.com/assets/21333614/18084410/707508b4-6ea7-11e6-9471-094b83ca6ac5.jpg)

**Comment by seresias** [comment]
Se me olvidó comentar, que pese a ser un bug de una versión anterior a la publicada ahora, no he visto nada en el changelog  parecido.

Y Gracias por vuestro trabajo...

**Comment by nosijf982** [comment]
Creo que eso no lo podemos solucionar,actualmente no existe ninguna cadena que contenga "Wilgotność".
A mi también me pasa con ese tema del Widget del reloj,así que supongo que eso es culpa del desarollador que en este caso no es MIUI,es nuestro compañero del foro de Xiaomi.eu, Acid.
Espero haber resuelto tus dudas :yum:

**Comment by jamflux** [comment]
@ingbrzy, could you check this please?

**Comment by Infante007** [comment]
Pues cerramos porque no es problema de la traducción.
Pregunta en el foro ,seguro que hay te contestan
un saludo
