### ISSUE TITLE
Botones auriculares in ear edición estándar

### ISSUE THREAD

**Issue by jmrodrigo** [ingbrzy/MA-XML-8.0-SPANISH#383]
Cuando se pulsa para contestar una llamada, subir o bajar volumen, no responde, o se sube o baja el volumen al máximo, teniendo que hacerlo desde el propio teléfono, Xiaomi redmi 2 4g.

**Comment by Infante007** [comment]
Lo siento pero es fallo de la rom no del idioma.
Pon la queja en el foro miui.eu
Un saludo ,cualquier problema con la traducción aquí estamos
