### ISSUE TITLE
Sugerencias/Errores de traducción

### ISSUE THREAD

**Issue by Abismo** [ingbrzy/MA-XML-8.0-SPANISH#387]
Pongo todos los que encontré aquí, espero que no sea demasiada molestia. Es por no crear un hilo nuevo para cada una...

En los ajustes del calendario falta traducir "Holidays" por "Festivos" o algo por el estilo.
![screenshot_2016-09-07-09-40-51-148_com android calendar](https://cloud.githubusercontent.com/assets/2502938/18391057/ecd071e8-76ac-11e6-9132-71176c1aa9b9.png)

En la app de Teléfono, al marcar un número como Spam, las opciones no están traducidas. Serían "Acoso", "Ventas", (no sé cómo leches se traduciría correctamente "Real estate" y "Courier" ya que no me parece que las inmobiliarias o los mensajeros sean spammers) y la última "Fraude".
![screenshot_2016-09-08-16-38-10-414_com miui yellowpage](https://cloud.githubusercontent.com/assets/2502938/18391202/7e38e502-76ad-11e6-963c-bdd2c5fce7b3.png)

A la hora de restringir permisos de una app del sistema, creo que se entendería mejor un "Denegar" en lugar de "Rechazar".
![screenshot_2016-09-09-13-32-07-519_com google android packageinstaller](https://cloud.githubusercontent.com/assets/2502938/18391274/b9867a48-76ad-11e6-9e56-79d2939fa60d.png)

En la app de Teléfono > Ajustes > Identificar números desconocidos > Protéjase contra el fraude el texto no está traducido. (De todas formas no parece haber ninguna funcionalidad aquí, pero ya que me lo encontré pues reporto). Creo que la traducción sería algo como "En los últimos años se han incrementado los casos de "alteración de números de teléfono por software" para imitar números de teléfono reales y realizar llamadas fraudulentas. Por favor preste atención: instituciones del gobierno, servicios postales, comercios electrónicos y compañías de transporte nunca van a solicitarle una transferencia de dinero o que ingrese dinero en una cuenta. Nunca van a solicitar su código PIN, número de cuenta o cualquier otra información privada. Durante las conversaciones telefónicas, no confíe en la gente que le pida que transfiera dinero, que devuelva o cambie un producto, que le dice que ha ganado un premio, que ha recibido una citación, que ha agotado ilegalmente su saldo bancario, que le informa sobre fondos insuficientes en su teléfono o que menciona blanqueo de dinero. Si usted recibe este tipo de llamadas puede tratar de identificar a la persona devolviendo la llamada y entonces reportarlo a la policía."
![screenshot_2016-09-09-13-36-19-690_com miui yellowpage](https://cloud.githubusercontent.com/assets/2502938/18391736/43441410-76af-11e6-8d80-080946bb317d.png)

Lo mismo ocurre con el menú "Acerca de esta función" de este mismo apartado:
![screenshot_2016-09-09-17-03-19-739_com miui yellowpage](https://cloud.githubusercontent.com/assets/2502938/18391822/998f89d0-76af-11e6-86ce-8ff211fdeeea.png)

Y en el menú general, donde dice "Lista de bloqueo", en lugar de "Las llamadas se grabarán automáticamente" debería poner "Activado" o algo por el estilo.
![screenshot_2016-09-09-17-04-47-681_com android phone](https://cloud.githubusercontent.com/assets/2502938/18391842/b2b3e884-76af-11e6-853f-80ad9113917d.png)

**Comment by Infante007** [comment]
No te preocupes @Abismo muchas gracias por ayudar y por avisar de los fallos.
¿cual era tu movil?
Un saludo

**Comment by Infante007** [comment]
Y importante ,
¿Que rom tienes ?

**Comment by Abismo** [comment]
Mi5, rom 6.9.9

**Comment by Abismo** [comment]
Perdón, 6.9.8

**Comment by Muchachito** [comment]
Corregido "Holidays" para próxima versión.

**Comment by Infante007** [comment]
El tema de:
 Y en el menú general, donde dice "Lista de bloqueo", en lugar de "Las llamadas se grabarán automáticamente" debería poner "Activado" o algo por el estilo.

Solucionado, revise la versión en ingles y tenias razón

**Comment by Infante007** [comment]
Hola @Abismo ,cierro el post se supone que esta todo solucionado ,
en el tema de Acerca de esta función y los textos grandes que estan en ingles ,no se puede traducir porque es conexion al servidor esta fuera del telefono.
Con la rom de esta semana nos avisas de cualquier problema
