### ISSUE TITLE
Notificaciones Wassap

### ISSUE THREAD

**Issue by jomoplaza** [ingbrzy/MA-XML-8.0-SPANISH#393]
Hola ayer actualice mi Red 1s con Miui 8 beta 6.9.8 y con el wifi en cualquier modo osea suspension, apagado.. no me entran los wass, ahora bien si uso datos si.
Sabemos el porque ??
O si hay alguna rom de miui 8 en la que no pase esto ??
Tengo dados permisos de autoarranque, el candadito...
Gracias

**Comment by Infante007** [comment]
Aqui es para problemas de traduccion, pero no problemas con las aplicaciones.
Le diste los permisos en la zona de ajustes/bateria y rendimiento/gestion de uso de la bateria en aplicaciones/si esta activado   ,procede a desactivarlo ,haber si asi te funciona el wassap

**Comment by jomoplaza** [comment]
Que va... ya lo hice y no hay manera.. pense que vosotros podias ayudarme,
gracias de todas maneras

**Comment by Infante007** [comment]
Un saludo
