### ISSUE TITLE
Detalles en inglés

### ISSUE THREAD

**Issue by marcosmanteca** [ingbrzy/MA-XML-8.0-SPANISH#403]
Hola buenas os paso unas capturas con detalles en inglés, tengo la última rom y mi dispositivo en Redmi Note 3 (MTK)
Muchas gracias por todo, un saludo.

![screenshot_2016-09-16-16-06-39-215_com android packageinstaller](https://cloud.githubusercontent.com/assets/11967463/18589445/167da58c-7c2b-11e6-9ac5-47639bd873de.png)
![screenshot_2016-09-16-16-06-25-563_com android packageinstaller](https://cloud.githubusercontent.com/assets/11967463/18589447/16848e2e-7c2b-11e6-8fcd-dd1222d9ea67.png)
![screenshot_2016-09-16-12-46-53-790_lockscreen](https://cloud.githubusercontent.com/assets/11967463/18589446/16833ab0-7c2b-11e6-8984-a1a67c7a638b.png)

**Comment by Infante007** [comment]
Hola @marcosmanteca  ahora mismo lo miro
un saludo

**Comment by Infante007** [comment]
@marcosmanteca  las dos primeras estan solucionadas, pero la tercera no la encuentro, dame mas detalles
despliegala y dime de donde te dice la galeria de donde es la foto

**Comment by marcosmanteca** [comment]
Me aparece en algunas ocasiones, te informo. Un saludo y gracias, seguiré
informando si ve alguna cosilla por ahí :).

2016-09-16 18:14 GMT+02:00 Infante007 <notifications@github.com>:

**Comment by Infante007** [comment]
@marcosmanteca  dame un pantallazo de los datos de tu movil, para ver los datos de version ,etc
es que no encuentro esa linea por el tipo de movil que nos dices

**Comment by marcosmanteca** [comment]
Ahi tienes. Gracias.
![screenshot_2016-09-17-02-30-16-627_com android settings](https://cloud.githubusercontent.com/assets/11967463/18604658/295b4732-7c7f-11e6-84ea-374e8d0f394d.png)

**Comment by Infante007** [comment]
Listo todo arreglado.
Un saludo
