### ISSUE TITLE
Compartir Internet

### ISSUE THREAD

**Issue by martigs** [ingbrzy/MA-XML-8.0-SPANISH#404]
Buenas tengo un Xiaomi red mi note 2 desde la versión muiui 8 no me deja compartir internet,  acabo de hacer una instalación limpia y me pasa lo mismo comparto el internet conecto desde el portátil la tablet o donde sea pero a la hora de navegar en el otro dispositivo no hay manera Salta que no se puede encontrar la página da red pero no Internet la conexión.

Saludos.

**Comment by nosijf982** [comment]
Lo siento pero aquí no te podemos ayudar,aquí solo solucionamos problemas en la traducción al español.
Saludos 😋

**Comment by Infante007** [comment]
Como dice mi compañero ,aqui solucionamos los problemas de traducción.
Comentalo en el foro de miui.eu ,aunque yo tambien tenia ese problema al principio de miui lo solucione siendo root y instalando un programa de thetering.(ISWAT Tether Unlocker)
