### ISSUE TITLE
Calendario y opciones nuevas

### ISSUE THREAD

**Issue by Abismo** [ingbrzy/MA-XML-8.0-SPANISH#410]
Dejo un par de cosas sin traducir:

En la app Calendario:
Dice al principio "Public holiday in". También pone "Valenciana" en lugar de "Valencia" o "Comunidad valenciana", pero no sé si eso es un error de traducción.
![screenshot_2016-09-14-10-33-04-631_com android calendar](https://cloud.githubusercontent.com/assets/2502938/18635915/273f74d2-7e87-11e6-9fd3-1907c2488ffe.png)

Entre paréntesis pone "regional holiday".
![screenshot_2016-09-14-10-35-02-061_com android calendar](https://cloud.githubusercontent.com/assets/2502938/18635939/450322c0-7e87-11e6-977d-1fe052d887dc.png)

En ajustes de captura de pantalla, aparece "Screenshot sound".
![screenshot_2016-09-19-16-30-45-123_com android settings](https://cloud.githubusercontent.com/assets/2502938/18635960/58f46140-7e87-11e6-938f-6b93ed63436a.png)

En ajustes sale "Default wallet".
![screenshot_2016-09-19-16-30-58-350_com android settings](https://cloud.githubusercontent.com/assets/2502938/18635983/6bc86582-7e87-11e6-9414-6d25dc2ee75f.png)

Todas las capturas son hechas con la ROM 6.9.15 en Mi5.

**Comment by nosijf982** [comment]
Gracias por avisar :yum

**Comment by nosijf982** [comment]
Lo del calendario no es culpa de la traducción,el calendario está sincronizado con la cuenta de Google y en el Calendario de Google lo pone así,lo digo porque en un móvil anterior que tuve con Android puro también me aparecería así los festivos. Muchas gracias de nuevo por ayudar,si encuentras algo más no dudes en decirnoslo. Saludos
