### ISSUE TITLE
Strings perdidos en traducción a español (ES).

### ISSUE THREAD

**Issue by EseLoKo** [ingbrzy/MA-XML-8.0-SPANISH#422]
Hola compañeros, 

No añado capturas, porque son bastantes strings, pero incluyo las traducciones a español que he encontrado que faltan en esta nueva versión de la ROM 6.9.22 para el Redmi Note 3 y que sí estaban presentes hasta ahora:

- Al cargar por primera vez: "Just a sec" o "Wait a sec"
- En el widget de reloj, los días y meses están en inglés, así como en la barra de notificaciones.
- Nombre de apps: "Messaging"
- Carpetas: "Tools", "Travel" 
- Cambio de fondo de pantalla: "Lock screen", "Home screen" (en el título del menú también)
- Apps: "Security" y todo en ella está en inglés

No he encontrado más faltas, porque tampoco he trasteado mucho más, pero todos estas cadenas estaban presentes en versiones anteriores.

Gracias por vuestro trabajo y espero que podáis revertir estos errores :)

Un saludo.

**Comment by Infante007** [comment]
Hola @EseLoKo , como comentas antes no tenías este problema  y desde que instalaste la ROM semanal te aparece en inglés.
Creemos que el problema era una aplicación que añadimos esta semana , esta borrada y las próximas semana estará solucionado .
Si ves que con la ROM de la próxima semana no se soluciona avisos. Un saludo
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/4a23302f900f112b28037e658715b915b5637062
