### ISSUE TITLE
Posible bug en la alarma

### ISSUE THREAD

**Issue by joseman160** [ingbrzy/MA-XML-8.0-SPANISH#426]
En versiones anteriores la alarma sonaba aún cuando el móvil estaba en silencio y en las última versión de la ROM para mi4c cuando el móvil está en silencio la alarma no suena, ¿podria ser un fallo o hay que poner alguna configuración distinta?

**Comment by Muchachito** [comment]
http://en.miui.com/thread-366045-1-1.html
