### ISSUE TITLE
Bloqueo de pantalla

### ISSUE THREAD

**Issue by Abismo** [ingbrzy/MA-XML-8.0-SPANISH#428]
Hay un par de fallos en el menú de ajustes de bloqueo de pantalla. Mi5, ROM semanal 6.9.29. Aparecen los "<u>" y falta la "ñ".

![screenshot_2016-09-30-16-31-11-097_com android settings](https://cloud.githubusercontent.com/assets/2502938/18995576/1c1dbe70-872d-11e6-978a-291326517dbf.png)
![screenshot_2016-09-30-16-31-35-542_com android settings](https://cloud.githubusercontent.com/assets/2502938/18995575/1c14590c-872d-11e6-878a-4ecb757c26e7.png)

**Comment by Abismo** [comment]
Y una tontería más: "Olvidó" debería llevar tilde. Ocurre aquí, y en el menú de Bloqueo de aplicaciones, no sé si en otros sitios también.

**Comment by Infante007** [comment]
Muchas gracias Abismo, ahora mismo lo arreglo.
Cualquier otra cosa, avisanos.
un saludo

**Comment by Infante007** [comment]
Hay tienes @Abismo  yo creo que con esto todo solucionado para la siguiente rom.
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/6ad32376d8e75215be31cd0fe1c215048e797e6e
