### ISSUE TITLE
Formato de fecha

### ISSUE THREAD

**Issue by FireChaka** [ingbrzy/MA-XML-8.0-SPANISH#430]
Hola, es una chorrada.. pero seria posible cambiar el formato de la fecha a "24 Septiembre" o "24 de Septiembre" en vez del formato ingles?

![screenshot_2016-09-24-00-29-31-355_com miui home](https://cloud.githubusercontent.com/assets/22405599/18999431/d5bf7d0e-873d-11e6-8bec-9b61edf46a22.png)

**Comment by Infante007** [comment]
hola @FireChaka , vamos a ver si se puede,
un saludo

**Comment by FireChaka** [comment]
Cambiando de idioma (a portugues por probar) parece que que si que se puede cambiar el formato jeje, gracias de antemano por el interés en esta chorrada la verdad. Saludos!
![screenshot_2016-09-30-19-04-18-691_com miui home](https://cloud.githubusercontent.com/assets/22405599/19000057/d6e0b1be-8740-11e6-9dc4-f34cde5586ad.png)

**Comment by Infante007** [comment]
ok,listo @FireChaka cambiado y para la proxima actualización,
No lo veras esta semana que viene porque los chinos estan de vacaciones y no sacaran rom
un saludo
