### ISSUE TITLE
Se repite número de fecha

### ISSUE THREAD

**Issue by jamflux** [ingbrzy/MA-XML-8.0-SPANISH#431]
![img_20161001_141827](https://cloud.githubusercontent.com/assets/17058685/19016581/b94b8afe-87e3-11e6-9412-801809dd5553.jpg)
![screenshot_2016-10-01-14-18-43-389_com miui home](https://cloud.githubusercontent.com/assets/17058685/19016582/b94d87be-87e3-11e6-8ce5-337fc37d36ef.png)

@ingbrzy, do you know where is this?

**Comment by ingbrzy** [comment]
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/blob/master/Spanish/main/MiuiSystemUI.apk/res/values-es/strings.xml#L200

**Comment by ingbrzy** [comment]
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/blob/master/Spanish/main/MiuiSystemUI.apk/res/values-es/strings.xml#L269

**Comment by jamflux** [comment]
Thanks for answer.
I will check if now is corrected.
