### ISSUE TITLE
Letra equivocada

### ISSUE THREAD

**Issue by Abismo** [ingbrzy/MA-XML-8.0-SPANISH#432]
En los ajustes de energía, en la explicación de las restricciones en segundo plano, dice "serrarán" en lugar de "cerrarán".

Mi5, ROM semanal 6.9.29.

![screenshot_2016-10-02-13-16-04-732_com miui powerkeeper](https://cloud.githubusercontent.com/assets/2502938/19020251/ca792884-88a3-11e6-8ea2-723d1b76b113.png)

**Comment by Muchachito** [comment]
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/a2302ad5bc160e2effa7845ed7b36ab8b7c46026
