### ISSUE TITLE
Cámara / Galería 

### ISSUE THREAD

**Issue by Abismo** [ingbrzy/MA-XML-8.0-SPANISH#433]
Mi5,  6.9.29

Al eliminar una foto debería decir algo como 'Eliminar de Mi Cloud' en lugar de lo que sale ahora. 

![screenshot_2016-10-03-14-22-21-681_lockscreen](https://cloud.githubusercontent.com/assets/2502938/19037228/74f0ff18-8975-11e6-958e-67bc68d98708.png)

**Comment by Abismo** [comment]
Y hay un espacio antes del signo de interrogación.

**Comment by Infante007** [comment]
Hola @Abismo ,con lo de eliminar de mi cloud ya esta bien . https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/3966640e05743e40c35ffc0bede2851503c1825c
Pero con el tema de el espacio no se puede hacer nada.
Un saludo
