### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by nosijf982** [ingbrzy/MA-XML-8.0-SPANISH#438]
@ingbrzy  Hello,I would like to know why the repository have Untranslatable strings. I deleted some strings a while ago but appears more strings in the log

http://translators.xiaomi.eu/XML_MIUI8-Spanish-es.html

**Comment by ingbrzy** [comment]
wait a while.. still updating list of allowed strings..

**Comment by ingbrzy** [comment]
OK done.. all what you see there can be removed...

**Comment by nosijf982** [comment]
Okaaay, Thank you 😋
