### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by CristhianEcheverry** [ingbrzy/MA-XML-8.0-SPANISH#440]
¡Hola!

Quería reportar este par de bugs

![img_20161006_144828](https://cloud.githubusercontent.com/assets/20938887/19169343/96957520-8bd9-11e6-9102-4ee3c046aa88.jpg)

![img_20161006_144917](https://cloud.githubusercontent.com/assets/20938887/19169344/969e0d5c-8bd9-11e6-95bc-48b7b30851ef.jpg)

Desearía aportar en futuras traducciones.

**Comment by Infante007** [comment]
Hola @CristhianEcheverry  el primer bug que comentas ya esta detectado y la proxima semana estara solucionado.
El segundo bug entiendo que es lo de Vd. , no es de importancia pero lo cambiamos por algo mas normal.
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/7fc6e20d2542b7a80ad8d9df9f8d7263ef0b1491

Toda ayuda es poca, asi que si quieres ayudar aqui estamos ,
un saludo

**Comment by Infante007** [comment]
@CristhianEcheverry  tienes cuenta de telegram?

**Comment by CristhianEcheverry** [comment]
Sí, +573188217546

**Comment by CristhianEcheverry** [comment]
Si encuentro alguna otra cosa la posteo.

**Comment by nosijf982** [comment]
Create un nick mejor y te explicamos como va 😉. Saludos.

**Comment by Infante007** [comment]
Pues si mejor borre el teléfono por seguridad.
Un saludo

**Comment by CristhianEcheverry** [comment]
Vale, estoy como @CristhianEcheverry, un saludo.
