### ISSUE TITLE
Fecha en Widget del Reloj

### ISSUE THREAD

**Issue by FireChaka** [ingbrzy/MA-XML-8.0-SPANISH#452]
Hola! Genial el cambio del formato de la fecha, Gracias jeje pero he visto que siguiendo la sintonia de las fechas por las distintas pantallas me he fijado que en el widget del reloj falta un "de", el otro widget  con el tiempo si esta correcta.

![deskclock](https://cloud.githubusercontent.com/assets/22405599/19406336/4afa107e-9284-11e6-9dcb-ead05701dd43.png)
![deskclock2](https://cloud.githubusercontent.com/assets/22405599/19406392/35594fcc-9285-11e6-95a2-e1e0681aaded.png)
Gracias por Vuestro Trabajo. Saludos!

**Comment by Infante007** [comment]
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/6ad5b25e30098505571c74be909cfe6af5a68a12 y https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/ede5b4d6b5b940314e25b353fd5e25954875a49b entiendo que ahora estara resuelto, la proxima avisa si ves que sigue igual.
un saludo

**Comment by FireChaka** [comment]
Hola! pues me temo que sigue igual :(
![fecha](https://cloud.githubusercontent.com/assets/22405599/19594398/267ef27c-9785-11e6-8566-8278885e6318.png)
