### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-8.0-SPANISH#455]
Hello @ingbrzy 
You can not give the word separation charging the parentheses.Thx
![photo_2016-10-16_13-37-12](https://cloud.githubusercontent.com/assets/18089036/19419255/f506a26c-93d3-11e6-9c07-5989090aab95.jpg)

**Comment by ingbrzy** [comment]
I can...

**Comment by Infante007** [comment]
When the battery is fully charged. There separation and aesthetically more beautiful looks.
Thank you very much
![photo_2016-10-16_19-20-36](https://cloud.githubusercontent.com/assets/18089036/19419349/d68e0b7a-93d5-11e6-8af8-b69f23a12f03.jpg)
