### ISSUE TITLE
y otra vez la fecha de widget :(

### ISSUE THREAD

**Issue by FireChaka** [ingbrzy/MA-XML-8.0-SPANISH#460]
Hola! como me dijiste que avisara si no se corregía el error pues ahi va... sigue faltando ese "de". Para ser concretos es en el widget de reloj 4x2. El otro, reloj+tiempo esta perfecto. Graciasss!!!
![fecha](https://cloud.githubusercontent.com/assets/22405599/19594551/cab0210e-9785-11e6-8bde-a494f3a94666.png)
Si no se puede pues no pasa naaa además es una chorradita.
Saludos!!!

**Comment by Infante007** [comment]
SI tienes razón, me pondre con ello
gracias

**Comment by Infante007** [comment]
Hello @ingbrzy 
one question please ? , What would be the correct date format
EEEE, d \'de\' MMMM
EEEE, d 'de' MMM

**Comment by ingbrzy** [comment]
EEEE, d \'de\' MMMM

**Comment by Infante007** [comment]
Thx

**Comment by Infante007** [comment]
@FireChaka esta vez esta solucionado seguro, la proxima semana si no es asi ,avisa
un saludo
