### ISSUE TITLE
Xiaomi MI 5 no conecta al 4G

### ISSUE THREAD

**Issue by gsuez** [ingbrzy/MA-XML-8.0-SPANISH#472]
Hola, me he comprado el MI 5 y tengo problema con al conexión LTE.
En Chile, mi compañía es Claro y funciona con la banda 7 (2.600mhz) que este teléfono soporta.
Pero no hay caso. Cambié la SIM por otra en Claro, 4G, y nada.
En el local me dijeron que podría ser la configuración APN, agregué una nueva pero tampoco.
¿Me pueden guiar con este caso, y si existen antecedentes de fallas del MI 5 con el 4G?

**Comment by Infante007** [comment]
Hola @gsuez  pense que era problema de idioma por eso te comente que vinieras aqui.
Cierto que el mi 5 tiene LTE , y ademas tu banda es la 2600.
Entiendo que tienes la ultima rom europea.
Hiciste una prueba de velocidad?
Puede ser que tengas 4g pero por problemas con la traduccion no te indique que estas en 4g.
Por poner un ejemplo.
Pusiste la la Sim en un telefono que tenga 4g y ver si tu compañia te de ese servicio?
Son ideas .

**Comment by gsuez** [comment]
Gracias por tu respuesta @Infante007.
Al cambiar idioma a inglés, muestra lo mismo, 3G.
Me falta poner la SIM en otro teléfono, creo que hoy podría hacerlo.
Nuevamente gracias :)
