### ISSUE TITLE
Widget clock 4x2 skins and spanish translation

### ISSUE THREAD

**Issue by rdgi** [ingbrzy/MA-XML-8.0-SPANISH#481]
Hi @ingbrzy.
Playing with widget clock 4x2 I've changed the skin. There are two or three skins developed by Acid (polish), and other developed by others, among them are MIUI.
Some skins use spanish translation but, for example, the skins developed by Acid are in Polish.
How can we translate these skins?
Where are the language resources of this skins/widgets?

Thank you in advance.

**Comment by ingbrzy** [comment]
you cant.. PL is hardcoded there..
