### ISSUE TITLE
Errores en aplicación de reloj

### ISSUE THREAD

**Issue by tururut** [ingbrzy/MA-XML-8.0-SPANISH#483]
Hola. Unas cositas que he notado en la traducción al español:

En la nueva opción de la aplicación del reloj (alarmas):
"Notificación**n** antes de sonar" --> sobra una "n"

En la descripción de esta opción pasa lo mismo:
 "Enviar una notificación**n** antes de sonar"

También en las opciones del reloj, creo que hay una traducción incorrecta. Una de las opciones es "La alarma sonará después de apagarla". En inglés pone "Alarm will ring after powered off" y creo que se refiere a que el móvil se pone en marcha automáticamente si está apagado para hacer sonar la alarma (aunque nunca he utilizado esta funcionalidad, por lo que pone [aquí](http://en.miui.com/thread-314836-1-1.html) parece que es eso). La traducción en ese caso tendría que ser algo así como "La alarma sonará con el teléfono apagado". Cuando desactivas la opción, el mensaje es igual, solo que en negativo.

Las cadenas que habría que cambiar en /Spanish/main/DeskClock.apk/res/values-es/strings.xml serían las siguientes:

<string name="setting_alarm_arriving_summary">Enviar una notificación antes de sonar</string>
<string name="setting_alarm_arriving_title">Notificación antes de sonar</string>

<string name="shutdown_alarm_disable_summary">La alarma no sonará con el teléfono apagado</string>
<string name="shutdown_alarm_enable_summary">La alarma sonará con el teléfono apagado</string>

**Comment by nosijf982** [comment]
Hola @tururut, muchísimas gracias por decirnoslo. Tienes razón lo de que la alarma sonará con el telefono apagado,ya está todo solucionado 😋
Saludos

**Comment by Infante007** [comment]
Contratado.....

**Comment by Infante007** [comment]
@tururut  muchas gracias, cualquier otra cosa nos lo dices y si quieres trabajar para mejorar la traducción bienvenido

**Comment by tururut** [comment]
Gracias a vosotros. La verdad es que mientras tenga un móvil con la ROM de Xiaomi.eu no me importaría echar una mano con la traducción. Si me decís qué hay que hacer, puedo probar a ver qué tal se me da.

**Comment by nosijf982** [comment]
Hola @tururutu

**Comment by nosijf982** [comment]
Hola @tururut , estaríamos encantados en nos ayudes. Necesitamos que tengas una cuenta de Telegram y que nos des tu nick para hablar con nosotros y ya te explicamos como va la cosa 😋

**Comment by tururut** [comment]
Mi nick en Telegram es el mismo que aquí: "tururut".
