### ISSUE TITLE
Radon no funciona

### ISSUE THREAD

**Issue by byjoaxel** [ingbrzy/MA-XML-8.0-SPANISH#491]
Pues eso, que el kernel radon no funciona con la ultima version de Xiaomi.eu

**Comment by Infante007** [comment]
Hola @byjoaxel  buenas noches:
Aquí solo tratamos temas relacionados con la traducción al español ,los problemas con el kernel y la ROM ,comentalo en el foro europeo.
Puede que te den alguna solución.
Un saludo
