### ISSUE TITLE
Translation improvements in XMRemoteController.apk

### ISSUE THREAD

**Issue by rdgi** [ingbrzy/MA-XML-8.0-SPANISH#499]
Hi @ingbrzy.
We are trying to improve the translation of XMRemoteController.apk but there are a lot of strings in chinese. 
We are working with the lastest version in Acid-miuipolskapl/v8-XML-Compare. Is this the last version? Have you got the latest global version?

Thank you in advance

**Comment by parenoeko** [comment]
actualizando 24/11/2016, error, mesanje que el sistema miui se ha detenido, e igual el proceso que usa la grafica. no deja hacer nada

**Comment by Infante007** [comment]
Hola @parenoeko aqui tratamos la traduccion al español.
Que telefono tienes .
Hiciste los wipes, puede ser fallo de tu telefono etc

**Comment by Infante007** [comment]
Parece que es un problema de la rom:
https://xiaomi.eu/community/threads/6-11-24.36315/page-9
Tienes que esperar a que las suban otra vez  o instala mientras la de la semana que viene
