### ISSUE TITLE
Las opciones de desarrollo no se pueden abrir en el lenguaje español

### ISSUE THREAD

**Issue by Dub4xDub4** [ingbrzy/MA-XML-8.0-SPANISH#523]
Al hacer aparecer las opciones de desarrollo, me doy cuenta que al abrirlas se cierran los ajustes. Si cambio de idioma esto no ocurre, estoy usando un Redmi Pro con la última versión de miui V8.1 estable de Xiaomi.eu

**Comment by Infante007** [comment]
Hola @Dub4xDub4 .
Tengo leído por el foro europeo que alguien le pasaba lo mismo, el tema teóricamente esta solucionado.
En la versión semanal de hoy ya estara solucionado  ,tu al tener la mensual tendrás que esperar un poco mas.
Cuando actualices a la mensual y si ves que sigue el problema pásate por aquí y nos avisas.
Un saludo
