### ISSUE TITLE
Developer options

### ISSUE THREAD

**Issue by numanolo** [ingbrzy/MA-XML-8.0-SPANISH#526]
I suffer FC when i go to developer options in stable 8.1.2.0
I push x5 in version ROM, then i go to more settings/ developer option and when i push it, FC comes.

I read something about permissions and com.mediatek.selfregister but i cant find it in apps. I found it in other versions, but not in this.

**Comment by ingbrzy** [comment]
fixed.. update MIUI version...

**Comment by ingbrzy** [comment]
fixed by https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/a9e9cc657d0684edc8ba5746078f39d55330a50d
