### ISSUE TITLE
Bug modo manual camara

### ISSUE THREAD

**Issue by AlejandroLA8** [ingbrzy/MA-XML-8.0-SPANISH#527]
Al tomar fotos modificando el tiempo de exposicion en el modo manual de la camara, por ejemplo 8 o 16 segundos, tarda el doble en tomar la foto, y finalmente no la toma con la exposicion seleccionada, y a veces acaba dando FC.

**Comment by Infante007** [comment]
Hola, @AlejandroLA8  si no te importa, pon tu telefono en idioma inglés, si te sigue ocurriendo es de la Rom y no del idioma español.
Un saludo
