### ISSUE TITLE
Contribution in spanish

### ISSUE THREAD

**Issue by 3tarazona** [ingbrzy/MA-XML-8.0-SPANISH#534]
Hi! I would like to make a contribution in your repository for Spanish. Let me know how can I help.

**Comment by Infante007** [comment]
Hola @3tarazona.
Claro sin problema, toda ayuda es bienvenida.
Tienes telegram?

**Comment by 3tarazona** [comment]
No tengo. Pero me puedes contactar por acá o por mi correo. Si tienes algún proyecto en especial en el cual estén trabajando ahora, dejame saber. Saludos.

**Comment by nosijf982** [comment]
Hola @3tarazona, si quieres ayudar necesitamos que te crees una cuenta de telegram, es gratis y solo nos tienes que dar tu alias(. Nos repartimos el trabajo allí. Aún así, si no quieres crearte la cuenta, puede hacer los cambios que creas convenientes creandote un fork y haciendo pulls requests. Saludos ;)

**Comment by Infante007** [comment]
Tambien si no quieres  puedes crear la cuenta de telegram en el portatil o pc y desde alli nos mantenemos en contacto

**Comment by Infante007** [comment]
Visto lo visto....
