### ISSUE TITLE
problem with tags <>

### ISSUE THREAD

**Issue by cocute** [ingbrzy/MA-XML-8.0-SPANISH#537]
In my redmi note 3 pro kate in spanish language in system messages show html tags same <>, fix please. Hide tags

**Comment by ingbrzy** [comment]
post screenshots...

**Comment by cocute** [comment]
![226614343_301851](https://cloud.githubusercontent.com/assets/7695898/22594564/da574344-ea23-11e6-85ab-fa857de5a63c.jpg)

**Comment by cocute** [comment]
i think show tags <b> </b>  in all system messages.

**Comment by ingbrzy** [comment]
do you have Xiaomi.eu ROM..?

**Comment by cocute** [comment]
this problem is in lastest EU dev versions in redmi note 3 KATE,
in EU stable version same model not problem

**Comment by cocute** [comment]
if i install lastest version  7.1.19/20
problem is solved?
ir i need wait for new versión?

**Comment by ingbrzy** [comment]
solved for next release..

**Comment by cocute** [comment]
ok thanks

**Comment by cocute** [comment]
hablas español?

otra cosa aparte de eso de los tags creo que la traducion de al menos ese mensaje no está bien,
debería ser "tenga acceso"  no   "pueda acceso"

**Comment by nosijf982** [comment]
Hola @cocute, tienes razón lo soluciono ahora mismo

**Comment by cocute** [comment]
lo de "pueda acceso" también lo habeis corregido?

**Comment by nosijf982** [comment]
Si está ya solucionado https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/e24e2e0ea21716a69a1edb2f63024a63480c56cc
