### ISSUE TITLE
Automatic Fixes in DeskClock.apk/res/values-es/arrays.xml

### ISSUE THREAD

**Issue by rdgi** [ingbrzy/MA-XML-8.0-SPANISH#546]
Hello @ingbrzy
I don't understand why automatic scripts are fixing new arrays in DeskClock.apk
Commit 858c384ad043ae1d2c9031baaa177bad2ef1d212
Arrays deleted: aqi_value and weather_tips_value

How do I know when an array/string will be fixed?

Thank you

**Comment by nosijf982** [comment]
No response
