### ISSUE TITLE
Translated lines that do not appear on the phones

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-8.0-SPANISH#550]
@ingbrzy
There are lines that are translated in the application cit and do not look like the phone, they still appear in English
There are lines of geminis and when looking at the phone continue to appear on the phone in English
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/blob/master/Spanish/main/Cit.apk/res/values-es/strings.xml

**Comment by Infante007** [comment]
@ingbrzy  Some answer?

**Comment by ingbrzy** [comment]
which device?

**Comment by Infante007** [comment]
geminis

**Comment by ingbrzy** [comment]
Cit.apk gemini doesnt use updated translation...
