### ISSUE TITLE
en la nueva versión 7.2.16 vuelve el problema de los tags

### ISSUE THREAD

**Issue by cocute** [ingbrzy/MA-XML-8.0-SPANISH#553]
en la nueva versión 7.2.16 vuelve el problema de los tags en los mensajes de permisos del sistema
![cameringo](https://cloud.githubusercontent.com/assets/7695898/23092363/3d83236a-f5c9-11e6-8e80-54981621394c.jpg)

**Comment by Infante007** [comment]
Hola @cocute  ya esta solucionado, muchas gracias por avisar.
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/b935c08a293f1e53af044fc010a3217e4a5437c0
