### ISSUE TITLE
icono spotify

### ISSUE THREAD

**Issue by dariancedres** [ingbrzy/MA-XML-8.0-SPANISH#578]
buenas el icono en spotify sale redondo con el fondo negro y tiene que ser todo verde, espero que lo puedan arreglar es en el redmi note 4x

**Comment by nosijf982** [comment]
Hola @dariancedres. Desde aquí no podemos arreglar eso, nosotros solo nos dedicamos al tema de la traducción de la ROM al español, puedes intentar comentar [en el foro](https://xiaomi.eu) sobre tu problema y a ver si ellos lo pueden arreglar. Un saludo ;)
