### ISSUE TITLE
Etiquetas en las solicitudes de permisos

### ISSUE THREAD

**Issue by r10sj** [ingbrzy/MA-XML-8.0-SPANISH#585]
En todas las ventanas de solicitud de permisos, se muestran las etiquetas html. Se adjunta captura de ejemplo.

Probado en Estable 8.0.22 para Xiaomi Mi5s
![captura_error_traduccion](https://cloud.githubusercontent.com/assets/9161929/24112217/1bcd76de-0d99-11e7-9490-38f8a892fb5a.png)

**Comment by Infante007** [comment]
Hola @r10sj  la estable ya se encuentra en la  8.2.2.0 y creo que el tema se soluciono.
Si puedes actualizar a la ultima y confirmalo
un saludo

**Comment by Infante007** [comment]
Como te comente ya se soluciono.
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/b935c08a293f1e53af044fc010a3217e4a5437c0
Si ves otra cosa nos avisas

**Comment by r10sj** [comment]
Disculpa, error mío. Es la versión 8.2.2.0 la que presenta estos errores. No parece que se haya solucionado completamente :(
