### ISSUE TITLE
Se muestran etiquetas html en las solicitudes de permisos.

### ISSUE THREAD

**Issue by r10sj** [ingbrzy/MA-XML-8.0-SPANISH#588]
En todas las ventanas de solicitud de permisos, se muestran las etiquetas html. Se adjunta captura de ejemplo.
![screenshot_2017-03-21-15-40-49-076_com android settings](https://cloud.githubusercontent.com/assets/9161929/24152901/4535823c-0e4d-11e7-8699-7c7230523f7f.png)
![screenshot_2017-03-21-15-41-18-566_com google android packageinstaller](https://cloud.githubusercontent.com/assets/9161929/24152900/43d3854c-0e4d-11e7-9b3e-7ff4fee6283f.png)

Probado en Estable 8.2.2.0 para Xiaomi Mi5s

**Comment by Infante007** [comment]
Te comento, tu actualización es del 18 febrero así que no veras que está solucionado.
Yo lo tengo semanal y mira cómo está corregido.
![screenshot_2017-03-21-06-46-49-358_com google android packageinstaller](https://cloud.githubusercontent.com/assets/18089036/24157337/67b3b854-0e59-11e7-8037-044419bb974b.png)
![screenshot_2017-03-21-06-44-45-384_com google android packageinstaller](https://cloud.githubusercontent.com/assets/18089036/24157354/710f1812-0e59-11e7-95ca-68c45aad0db7.png)
![screenshot_2017-03-21-06-44-25-264_com google android packageinstaller](https://cloud.githubusercontent.com/assets/18089036/24157366/797f5b1a-0e59-11e7-84b9-9e80d2e3039c.png)

**Comment by r10sj** [comment]
Genial. Muchas gracias por el currazo.

**Comment by r10sj** [comment]
Acabo de actualizar a 8.2.3, y ahora ya sale todo perfectamente. Muchas gracias
