### ISSUE TITLE
Traducción no completa al programar una alarma

### ISSUE THREAD

**Issue by r10sj** [ingbrzy/MA-XML-8.0-SPANISH#596]
A la hora de programar una alarma, el texto que indica el tiempo restante hasta que salte, no está completamente traducido. Adjunto captura como ejemplo

Versión 8.2.3 de Mi5S
![screenshot_2017-03-30-23-38-23-233_com android deskclock](https://cloud.githubusercontent.com/assets/9161929/24549265/cc14a0c6-1618-11e7-9a76-a3b365c35e3c.png)

**Comment by nosijf982** [comment]
Hola @r10sj, gracias por avisar lo revisaremos lo antes posible. Si encuentras algún error más avísanos ;) 
Saludos

**Comment by nosijf982** [comment]
Es una versión estable o semanal?

**Comment by Infante007** [comment]
Hola @r10sj como te muestro en la imagen ya está solucionado.
En la siguiente actualización ya lo tendrás bien
![screenshot_2017-04-01-10-02-41-039_com android deskclock](https://cloud.githubusercontent.com/assets/18089036/24576776/893ae972-16c2-11e7-877c-9d316144aaa9.png)

**Comment by r10sj** [comment]
Sois muy grandes. Muchas gracias!!!!

**Comment by Infante007** [comment]
@r10sj Muchas a ti por avisar de esos fallos.
un abrazo y cierro
