### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-8.0-SPANISH#604]
@ingbrzy 
What are you doing that there are phrases that appear in English and are translated?

**Comment by ingbrzy** [comment]
Magic....

**Comment by Infante007** [comment]
The question is that he is fucking the job, it makes you funny ... not me

**Comment by ingbrzy** [comment]
Sorry ma magic glass ball is broken...
I have no idea what you try to report here...

**Comment by nosijf982** [comment]
![archivo](https://cloud.githubusercontent.com/assets/16381926/24835968/108d48d6-1d10-11e7-9b5d-309763e79aeb.jpg)

https://github.com/ingbrzy/MA-XML-8.0-SPANISH/blob/master/Spanish/main/MiuiKeyguard.apk/res/values-es/strings.xml#L27

I don't understand why the string isn't translated in ROM

**Comment by ingbrzy** [comment]
This string was added in 7.4.6... so your translation will be included next week...

**Comment by Infante007** [comment]
Hello, and the 4G change and now it looks LTE?
It was set to be seen 4G.
It's just curiosity
![photo_2017-04-08_14-07-44](https://cloud.githubusercontent.com/assets/18089036/24836352/0d7467ce-1d1a-11e7-85d6-19f5ac4732f5.jpg)

**Comment by ingbrzy** [comment]
Its not taken from translation...

**Comment by Infante007** [comment]
ok, Thx
