### ISSUE TITLE
Temporizador Radio FM

### ISSUE THREAD

**Issue by uriana** [ingbrzy/MA-XML-8.0-SPANISH#607]
![screenshot_2017-04-18-04-50-27-752_com miui fm](https://cloud.githubusercontent.com/assets/15260759/25114394/ba5af4a4-23fe-11e7-940e-0e330f002cba.png)
Temporizador Radio FM en Inglés

**Comment by Infante007** [comment]
Buenos días @uriana  muchas gracias por avisar, ya esta corregido ,cualquier otra cosa avisa.
un saludo
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/19734709e0a9317fbcfae279376e2745c53973f9
