### ISSUE TITLE
Cadena sin traducir en historico de llamadas

### ISSUE THREAD

**Issue by r10sj** [ingbrzy/MA-XML-8.0-SPANISH#610]
En el histórico de llamadas, el numero de veces que sonó cierto número aparece en ingles. Ejemplo de rom 8.2.4.0 para Mi5S
![screenshot_2017-04-20-08-11-54-648_com android contacts](https://cloud.githubusercontent.com/assets/9161929/25220358/d05bf85c-25b1-11e7-8af1-d1451a21319d.png)

**Comment by ingbrzy** [comment]
not translation issue.. 
this translation was removed from stables to avoid FC as variable changed for current translation and in the stables are still old one...
