### ISSUE TITLE
barra de estado

### ISSUE THREAD

**Issue by joseman160** [ingbrzy/MA-XML-8.0-SPANISH#645]
Cuando abres la aplicación de Instagram la barra de estado con la hora, la batería y la señal no se ven porque adquieren el mismo color blanco y no se distinguen

**Comment by nosijf982** [comment]
Hola, @joseman160. Desde aquí no podemos arreglar eso, nosotros solo nos dedicamos al tema de la traducción de la ROM al español, puedes intentar comentar en el foro sobre tu problema y a ver si ellos lo pueden arreglar. Un saludo ;)

**Comment by joseman160** [comment]
Gracias, un saludo
