### ISSUE TITLE
Lock screen charging info cut off.

### ISSUE THREAD

**Issue by Gingernut1978** [ingbrzy/MA-XML-8.0-SPANISH#668]
Spanish translation is too long or text too big for text boxes cutting off parts of words.

Capture:
https://drive.google.com/file/d/0B2D34YVbNxk-M2RSdnNDeC1NN1E/view?usp=drivesdk

**Comment by nosijf982** [comment]
Tomamos nota, lo antes posible lo solucionamos la próxima semanas debería estar solucionados.
Saludos

**Comment by Infante007** [comment]
Hola @Gingernut1978 buenas tardes.
Como dice mi compañero @nosijf982  lo solucionaremos para la siguiente version.
Gracias

**Comment by Gingernut1978** [comment]
Gracias
