### ISSUE TITLE
Wrong file naming when you use the camera

### ISSUE THREAD

**Issue by juankar7** [ingbrzy/MA-XML-8.0-SPANISH#672]
While with global version it's ok, using weekly ROM from Xiaomi.eu causes wrong file naming when you use the camera. It happened to me with my last MI5s too:

Original naming: IMG_yyyymmdd.jpg (i.e IMG_20170713_143927.jpg)
Xiaomi.eu naming: IMG_ddmmyyyy.jpg (i.e IMG_03082017_140839.jpg)

The problem is when you see the photos in a PC, they have a random order, not by date.

¿Is there any fix for that ROM issue? i don't mean a PC application for ordering, but it could be a first step.

**Comment by ingbrzy** [comment]
fixed in MIUI 9
