### ISSUE TITLE
Errores traducción

### ISSUE THREAD

**Issue by migui88** [ingbrzy/MA-XML-8.0-SPANISH#673]
Hola,
Tengo un redmi 3 con versión 8.5.2.0 y resulta que hay varias cosas que no están traducidas. Cuando pongo el movil a cargar aparece "Charging" en vez de "cargando". Cuando voy a almacenamiento aparece "storage" en vez de "¿memoria?(no se si sería esta la traducción)". También me he dado cuenta que cuando meto música la aplicación nativa de Música me salta diciendo que "XX songs added" en vez de "xxx canciones añadidas". Os paso capturas para que veais el problema. 
Saludos y gracias por vuestro aporte!!!
![screenshot_2017-09-24-13-43-35-217_com miui home](https://user-images.githubusercontent.com/10882140/30782278-32f5858e-a12f-11e7-995c-4a3451e090bd.png)
![screenshot_2017-09-24-13-43-11-809_com android fileexplorer](https://user-images.githubusercontent.com/10882140/30782279-32fbfea0-a12f-11e7-88b2-eb7017267092.png)
![screenshot_2017-09-24-13-43-35-217_com miui home - copia](https://user-images.githubusercontent.com/10882140/30782288-73cb34aa-a12f-11e7-86c7-7d8768a515b2.png)

**Comment by rdgi** [comment]
Buenos días.
En la versión de desarrollo que yo tengo instalada en mi móvil (Redmi 3 Pro) las traducciones están correctas, así que me imagino que en la próxima versión estable de la ROM estará todo solucionado. De todos modos lo miraré.

Una pregunta, ¿la ROM que tienes está basada en MIUI 9? Si me haces una captura de la versión de la ROM mejor.

Un saludo

**Comment by migui88** [comment]
Hola,
Te paso unas capturas de otros errores de traducción que he visto y también de mi versión de MIUI. 
Saludos!
![screenshot_2017-09-24-14-31-52](https://user-images.githubusercontent.com/10882140/30801950-483a275e-a1e5-11e7-803f-3908e8332918.png)
![screenshot_2017-09-24-23-33-49](https://user-images.githubusercontent.com/10882140/30801946-483525ec-a1e5-11e7-9957-8ca1c50f497a.png)
![screenshot_2017-09-24-23-37-46](https://user-images.githubusercontent.com/10882140/30801949-4837db2a-a1e5-11e7-945c-f77dac63e64f.png)
![screenshot_2017-09-24-23-38-52](https://user-images.githubusercontent.com/10882140/30801947-483709b6-a1e5-11e7-9c8a-e55f8ba93130.png)
![screenshot_2017-09-25-11-20-45](https://user-images.githubusercontent.com/10882140/30801948-4837a484-a1e5-11e7-868f-3172806def22.png)
![screenshot_2017-09-25-11-27-38](https://user-images.githubusercontent.com/10882140/30801951-483ac66e-a1e5-11e7-8b07-45824eee461e.png)

**Comment by nosijf982** [comment]
Creo que tienes la rom bastante desactualizada, prueba a actualizar y nos cuentas ;)

**Comment by nosijf982** [comment]
Miento,está actualizada. Seguramente las frases que nos las cargariamos porque en las versiones más modernas no tienen esas líneas. Te recomiendo actualizar a MIUI 9 cuando puedas en la versión semanal

**Comment by migui88** [comment]
Hola,
Pues es que me acabo de flashear esta versión porque es la última estable que he visto. No sabrás cuando va a salir MIUI9 estable, no? Mínimo un mes, supongo... Estaré al tanto cuando salga por si detecto algún error de traducción, pero estando ya MIUI8 tan depurada, no creo que aparezca ninguno.
Saludos!

**Comment by nosijf982** [comment]
No lo sé la verdad, siento mucho esos errores. Cuando instales la nueva si encuentras los mismo o otros fallos te agradeceríamos muchísimo que nos avises ;)

**Comment by migui88** [comment]
Tengo un redmi 4 al que pensaba ponerle la MIUI 8 estable, pero ya que tengo que flashear, voy a flashearle primero la última semanal de MIUI9 que hay para ver si encuentro errores y luego ya le flaseo la MIUI8 estable. Ya comentaré cuando haya hecho las verificaciones.

**Comment by nosijf982** [comment]
Perfecto, nos cuentas ;)

**Comment by migui88** [comment]
Hola,
He instalado la versión MIUI9 semanal, te abro unos issues en la rama de MIUI9, cierro esta?
Saludos

**Comment by nosijf982** [comment]
Ya lo he visto, te comento allí ya
